### ISSUE TITLE
Add Package.swift definition

### ISSUE THREAD

**Issue by aplr** [borchero/Squid#1]
As a package developer I want to copy/paste the dependency definition from the readme, which is missing here. You could add sth like that to the readme to simplify usage:

> If you are developing a Swift package, adding Squid as a dependency is as easy as adding it to the dependencies value of your Package.swift like so:

```swift
dependencies: [
    .package(url: "https://github.com/borchero/Squid.git", from: "1.0.0")
]
```

See my PR #2

**Comment by borchero** [comment]
Fixed by PR #2
