### ISSUE TITLE
http instead of https?

### ISSUE THREAD

**Issue by kevinrenskers** [borchero/Squid#21]
I'm using a local development server, which doesn't work over http. Yet Squid always loads everything over https. I see there's a `usesSecureProtocol` property but that has to be specified per request, not on the `HttpService` level. Am I missing something? 🤔

**Comment by borchero** [comment]
Check out https://github.com/borchero/Squid/releases/tag/1.5.0 ;)

**Comment by kevinrenskers** [comment]
Awesome, thanks!
