### ISSUE TITLE
Request headers not updating when retrying

### ISSUE THREAD

**Issue by jedwardblack** [borchero/Squid#6]
I am using the retrier and updating the stateful service that provides the accessToken & refreshToken values exactly as is shown in your example, but the retried request always uses the values from the original request, not the updated values.

Is there any way to change the header values before retrying the request?

**Comment by borchero** [comment]
The issue was that `Future` caches the value that it first returned so the request was not built again ... it is fixed now, I'll draft a new release shortly.
