### ISSUE TITLE
Paginator examples?

### ISSUE THREAD

**Issue by AAAstorga** [borchero/Squid#9]
I love this library, it is awesome. Could you write some Paginator examples? I have parts of my app where I want to have an endless scroll while loading more data from the server, but not sure on how to use Paging properly in Squid!

Thanks again :)

**Comment by borchero** [comment]
Will do on the weekend ;)

**Comment by AAAstorga** [comment]
Any update? 😄

**Comment by borchero** [comment]
Sorry for the delay, I've been working on the other issue and wanted to commit the documentation along with that ... should be done within 24 hours though ;)

**Comment by borchero** [comment]
Done ;) https://borchero.github.io/Squid/04-pagination.html
